### ISSUE TITLE
color changed

### ISSUE THREAD

**Issue by luoww1992** [CVMI-Lab/VideoDemoireing#2]
the video's color is changed ?
will the model change the color space ?
how to change the color to original ?
i want to download the data from the project, but it is too slow , can you share a link with baidudisk?

**Comment by daipengwa** [comment]
- This is due to the training dataset. The color of captured moire videos are degraded by the phone we used, thus training on such dataset, our model learns to simultaneously remove the moire artifacts and enhance the color tone.  
- If you want to change the color to orginal, I suggets that you can try some works focusing on color tone, such as histgram match.    
- You can download via this link: 
Link: https://pan.baidu.com/s/18evBGvTHwN2lL2Oo7ao8-Q    Password: b28v

**Comment by luoww1992** [comment]
@daipengwa 
i have test it in datav2, it is good. 
Q1: now i want to make a new train dataset, how to make it , can you give me some advises about it ? 
Q2: can you share some original moire videos to be as reference for me  when i make the train dataset ?
thank you !

**Comment by daipengwa** [comment]
- Please follow the code in 'dataset_prepare/' for preparing your own training dataset. 
- The original captured moire videos can be found 'https://www.dropbox.com/home/cvpr2022_VDmoire/original'. For clean videos, you can write the clean frames in our training dataset as videos.
